version: '3.8'

services:
  rector_bot:
    build: .
    container_name: rector_feedback_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Tashkent
    working_dir: /app

networks:
  bot_network:
    driver: bridge